version: '3'

dotenv: ['.env', '{{.HOME}}/.env']

tasks:
  install:
    desc: "Install the package in editable mode"
    cmds:
      - .venv/bin/python -m pip install --trusted-host pypi.org --trusted-host pypi.python.org -U pip setuptools wheel
      - .venv/bin/python -m pip install --trusted-host pypi.org --trusted-host pypi.python.org -e .[dev,build,examples]
  install:venv:
    desc: "Install venv"
    cmds:
      - python3 -m venv .venv
  install:all:
    desc: Install all packages in editable mode, including creating venv"
    cmds:
      - task: install:venv
      - task: install

  clean:
    desc: "Clean the build files"
    cmds:
      - rm -rf build/ dist/ src/*.egg-info/ .mypy_cache/ .pytest_cache/ .coverage .scannerwork
      - rm -rf docs/coverage/ tests/coverage.xml
  clean:venv:
    desc: "Clean .venv"
    cmds:
      - rm -rf .venv
  clean:caches:
    desc: "Clean caches"
    cmds:
      - ruff clean
      - find . -type d -name "__pycache__" -exec rm -r {} +
  clean:all:
    desc: "Clean all"
    cmds:
      - task: clean
      - task: clean:caches 
      - task: clean:venv

  build:all:
    desc: "Build all artifacts"
    cmds:
      - task: build
  build:
    desc: "Build the package"
    cmds:
      - python -m build

  run:svc:
    desc: "Run the JFind service"
    cmds:
      - python -m src.jfind_svc.main

  format:
    desc: "Format the code using ruff"
    cmds:
      - ruff format
      - ruff check --select I --fix .

  check:
    desc: "Check code by linting"
    cmds:
      - ruff check

  check:fix:
    desc: "Check code and try to fix it"
    cmds:
      - ruff check --fix

  test:
    desc: "Run the tests using pytest"
    cmds:
      - pytest
  test:cov:
    desc: "Run the tests using pytest with coverage"
    cmds:
      - pytest --cov src --cov-report html:docs/coverage --cov-report xml:tests/coverage.xml -x

  pre-commit:
    desc: "Run before commit"
    cmds:
      - task: format
      - task: check
      - task: test

  ci:
    desc: "Run the CI pipeline"
    cmds:
      - task: check
      - task: test
    deps:
      - install:all
