version: '3'

vars:
  BINARY_TARGET: ./bin
  BINARY_NAME: '{{.BINARY_TARGET}}/jfind'

tasks:
  build:
    desc: Build for current platform
    cmds:
      - go build -o {{.BINARY_NAME}}

  build:all:
    desc: Build for all supported platforms
    cmds:
      - GOOS=darwin GOARCH=amd64 go build -o {{.BINARY_NAME}}-darwin-amd64
      - GOOS=darwin GOARCH=arm64 go build -o {{.BINARY_NAME}}-darwin-arm64
      - GOOS=linux GOARCH=amd64 go build -o {{.BINARY_NAME}}-linux-amd64
      - GOOS=windows GOARCH=amd64 go build -o {{.BINARY_NAME}}-windows-amd64.exe

  clean:
    desc: Clean build artifacts
    cmds:
      - go clean
      - rm -f {{.BINARY_NAME}}*

  default:
    desc: List available tasks
    cmds:
      - task --list --sort alphanumeric

  test:
    desc: Run tests
    cmds:
      - go test -v ./...
